server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Chamadas /api vão para o container da API (rede interna do Docker)
    location /api/ {
        proxy_pass http://api:3333;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # React Router: qualquer rota volta para o index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}